version: '1.0'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: payments_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - payments-network


networks: 
  payments-network:
    driver: bridge
